const CHANGE_MUSIC = 'CHANGE_MUSIC';
const LOAD_MUSIC = "LOAD_MUSIC";
const SAVE_MUSIC = "SAVE_MUSIC";
const DEL_MUSIC = "DELETE_MUSIC";
const CHANG_ALL_MUSIC = "CHANG_ALL_MUSIC";
export {
  CHANGE_MUSIC,
  LOAD_MUSIC,
  SAVE_MUSIC,
  DEL_MUSIC,
  CHANG_ALL_MUSIC
}
